-- MySQL Script generated by MySQL Workbench
-- mar 19 sep 2017 01:42:32 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id2961679_alquiler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id2961679_alquiler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id2961679_alquiler` DEFAULT CHARACTER SET utf8 ;
USE `id2961679_alquiler` ;

-- -----------------------------------------------------
-- Table `id2961679_alquiler`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id2961679_alquiler`.`departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2961679_alquiler`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id2961679_alquiler`.`provincia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  `iddepartamento` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `prov.depa_idx` (`iddepartamento` ASC),
  CONSTRAINT `prov.depa`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `id2961679_alquiler`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2961679_alquiler`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id2961679_alquiler`.`distrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  `idprovincia` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `dist.prov_idx` (`idprovincia` ASC),
  CONSTRAINT `dist.prov`
    FOREIGN KEY (`idprovincia`)
    REFERENCES `id2961679_alquiler`.`provincia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2961679_alquiler`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id2961679_alquiler`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2961679_alquiler`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id2961679_alquiler`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `fotografia` VARCHAR(200) NULL,
  `idtipousuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usua.tipou_idx` (`idtipousuario` ASC),
  CONSTRAINT `usua.tipou`
    FOREIGN KEY (`idtipousuario`)
    REFERENCES `id2961679_alquiler`.`tipousuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id2961679_alquiler`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id2961679_alquiler`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `apepater` VARCHAR(45) NULL,
  `apemater` VARCHAR(45) NULL,
  `nombres` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `iddistrito` INT NULL,
  `idusuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `clie.dist_idx` (`iddistrito` ASC),
  INDEX `clie,usua_idx` (`idusuario` ASC),
  CONSTRAINT `clie.dist`
    FOREIGN KEY (`iddistrito`)
    REFERENCES `id2961679_alquiler`.`distrito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clie,usua`
    FOREIGN KEY (`idusuario`)
    REFERENCES `id2961679_alquiler`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
